### ISSUE TITLE
Repository dispatch action

### ISSUE THREAD

**Issue by staticaland** [oslokommune/composite-actions#1]
Use curl and use https://github.com/peter-evans/repository-dispatch/blob/main/action.yml

https://gist.github.com/Daniel-ltw/552b90800b07c22e4a83dfa68ada6318

Never mind, use OctoKit instead:

```yml
    - name: Deploy Stage
      uses: actions/github-script@v5
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            'Mause',
            'fdroidrepo',
            'workflows/update.yaml',
            'main',
          });
```

```yml
 - name: Bundle
    id: bundle
    if: ${{ steps.changesets.outputs.published == 'true' }}
    uses: actions/github-script@v6
    with:
      script: |
        try {
          const result = await github.rest.actions.createWorkflowDispatch({
            owner: 'asdads',
            repo: 'asdasd',
            workflow_id: 'abc.yml',
            ref: 'main',
            inputs: {
              tags: ${{ steps.docker.id }}
            },
          })
          console.log(result);
        } catch(error) {
          console.error(error);
          core.setFailed(error);
        }
```
